name: malina_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^9.0.0
  flutter_svg: ^2.0.17
  equatable: ^2.0.7
  get_it: ^8.0.3
  mobile_scanner: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/selected/
    - assets/icons/unselected/
    - assets/images/